import type { APIRoute } from "astro";
import { ROUTES, type RouteKey, type Locale } from "../lib/content";
import { SITE_URL } from "../lib/site";

/**
 * Hand-rolled rather than generated by @astrojs/sitemap.
 *
 * That integration pairs locales by matching slugs, so it expects /foo and
 * /en/foo. Our slugs are translated, so /anvandarvillkor and /en/terms are the
 * same page in two languages and it cannot tell. The result was a sitemap where
 * only the home page carried its alternates.
 *
 * ROUTES already holds every pairing, so building the file from that gives
 * correct xhtml:link alternates on every entry, and stays right automatically
 * whenever a route is added there.
 */

// Shared with the canonical tags rather than restated, so the sitemap cannot
// advertise one origin while every page canonicalises to another.
const SITE = SITE_URL.replace(/\/+$/, "");

// Rough guidance for crawlers on relative importance. The home pages matter
// most, legal pages least.
const PRIORITY: Record<RouteKey, string> = {
  home: "1.0",
  about: "0.8",
  // The guide is the page most likely to earn links and answer a search
  // directly, so it ranks alongside the home page rather than below about.
  guideFibc: "0.9",
  // The flagship product page, and the main commercial landing target.
  productFibc: "0.9",
  privacy: "0.3",
  terms: "0.3",
  cookies: "0.3",
};

const LOCALES: Locale[] = ["sv", "en"];

const abs = (path: string) => `${SITE}${path === "/" ? "" : path}`;

export const GET: APIRoute = async () => {
  const entries: string[] = [];

  for (const key of Object.keys(ROUTES) as RouteKey[]) {
    for (const locale of LOCALES) {
      // Every entry lists all languages of the page, including itself, which
      // is what the spec asks for.
      const alternates = LOCALES.map(
        (l) =>
          `    <xhtml:link rel="alternate" hreflang="${l === "sv" ? "sv-SE" : "en"}" href="${abs(ROUTES[key][l])}" />`,
      ).join("\n");

      entries.push(
        [
          "  <url>",
          `    <loc>${abs(ROUTES[key][locale])}</loc>`,
          alternates,
          `    <xhtml:link rel="alternate" hreflang="x-default" href="${abs(ROUTES[key].sv)}" />`,
          `    <changefreq>${key === "home" ? "weekly" : "yearly"}</changefreq>`,
          `    <priority>${PRIORITY[key]}</priority>`,
          "  </url>",
        ].join("\n"),
      );
    }
  }

  const xml = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
    '        xmlns:xhtml="http://www.w3.org/1999/xhtml">',
    entries.join("\n"),
    "</urlset>",
  ].join("\n");

  return new Response(xml, {
    headers: { "content-type": "application/xml; charset=utf-8" },
  });
};
